#!/usr/bin/env python3
"""Floating WhatsApp + Zalo buttons for every public page: ONE snippet, TWO languages.

Writes the block below just before </body> of each page, between the markers.
Language follows <html lang="..."> (vi / en); only the aria-labels differ.
Styles: assets/floating-contact.css (linked from inside the block, so <head> is never touched).
Clicks are already tracked by the site-wide listener in each page's <head>
(wa.me -> whatsapp_click, zalo.me -> zalo_click, plus Meta Pixel Contact); no JS here.

Run from the repo root:  python3 tools/floating-contact.py
Idempotent: re-running replaces the existing block. Run again after adding new pages.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = '<!-- floating-contact:start (generated by tools/floating-contact.py; edit there, not here) -->'
END = '<!-- floating-contact:end -->'

# Verified: same numbers as every existing contact link and the LocalBusiness schema.
WA = 'https://wa.me/84777986999'
ZALO = 'https://zalo.me/0777986999'

LABELS = {
    'vi': ('Nhắn tin cho Manh Long Optical qua WhatsApp', 'Nhắn tin cho Manh Long Optical qua Zalo', 'Liên hệ nhanh'),
    'en': ('Chat with Manh Long Optical on WhatsApp', 'Chat with Manh Long Optical on Zalo', 'Quick contact'),
}

WA_ICON = ('<svg viewBox="0 0 24 24" width="34" height="34" fill="currentColor" aria-hidden="true" focusable="false">'
           '<path d="M17.47 14.38c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.16-.17.2-.35.22-.64.07-.3-.15-1.26-.46-2.39-1.47-.88-.79-1.48-1.76-1.65-2.06-.17-.3-.02-.46.13-.6.13-.14.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.03-.52-.07-.15-.67-1.61-.92-2.2-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.48s1.07 2.88 1.21 3.07c.15.2 2.1 3.2 5.08 4.49.71.31 1.26.49 1.7.63.71.22 1.36.19 1.87.12.57-.09 1.76-.72 2-1.41.25-.7.25-1.29.18-1.41-.08-.13-.28-.2-.57-.35Z"/>'
           '<path d="M20.52 3.45A11.8 11.8 0 0 0 12.05 0C5.5 0 .16 5.34.16 11.89c0 2.1.55 4.14 1.59 5.95L.06 24l6.3-1.65a11.9 11.9 0 0 0 5.68 1.45h.01c6.55 0 11.89-5.34 11.89-11.89 0-3.18-1.24-6.16-3.48-8.41ZM12.05 21.79h-.01a9.87 9.87 0 0 1-5.03-1.38l-.36-.21-3.74.98 1-3.65-.24-.37a9.86 9.86 0 0 1-1.51-5.26c0-5.45 4.44-9.88 9.9-9.88 2.64 0 5.12 1.03 6.98 2.9a9.82 9.82 0 0 1 2.9 6.99c0 5.45-4.44 9.88-9.89 9.88Z"/></svg>')

ZALO_ICON = ('<svg viewBox="0 0 48 48" width="44" height="44" aria-hidden="true" focusable="false">'
             '<text x="24" y="29.5" text-anchor="middle" fill="currentColor" font-family="Arial,Helvetica,sans-serif" '
             'font-size="15.5" font-weight="700" letter-spacing="-.2">Zalo</text></svg>')


def block(lang):
    wa_label, zalo_label, group_label = LABELS[lang]
    return (
        f'{START}\n'
        '<link rel="stylesheet" href="/assets/floating-contact.css">\n'
        f'<div class="floating-contact" role="group" aria-label="{group_label}">\n'
        f'  <a class="floating-contact__button floating-contact__button--whatsapp" href="{WA}" target="_blank" rel="noopener noreferrer" aria-label="{wa_label}">{WA_ICON}</a>\n'
        f'  <a class="floating-contact__button floating-contact__button--zalo" href="{ZALO}" target="_blank" rel="noopener noreferrer" aria-label="{zalo_label}">{ZALO_ICON}</a>\n'
        '</div>\n'
        f'{END}\n'
    )


SKIP_DIRS = {'.git', 'docs', 'templates', 'vendor', 'tools'}
BLOCK_RE = re.compile(re.escape(START) + r'.*?' + re.escape(END) + r'\n?', re.S)


def eligible(path, text):
    if any(part in SKIP_DIRS for part in path.relative_to(ROOT).parts):
        return False, 'excluded dir'
    if path.name.startswith('google') and len(text) < 200:
        return False, 'search-console verification file'
    if 'http-equiv="refresh"' in text:
        return False, 'redirect stub'
    if '</body>' not in text:
        return False, 'no </body>'
    return True, ''


def main():
    changed, skipped = [], []
    for path in sorted(ROOT.rglob('*.html')):
        text = path.read_text(encoding='utf-8')
        ok, why = eligible(path, text)
        if not ok:
            skipped.append((path, why))
            continue
        m = re.search(r'<html[^>]*\blang="([a-zA-Z]+)', text)
        lang = 'vi' if (m and m.group(1).lower() == 'vi') else 'en'
        new = BLOCK_RE.sub('', text)
        idx = new.rfind('</body>')
        new = new[:idx] + block(lang) + new[idx:]
        if new != text:
            path.write_text(new, encoding='utf-8')
            changed.append((path, lang))
    for p, lang in changed:
        print(f'  updated [{lang}] {p.relative_to(ROOT)}')
    for p, why in skipped:
        print(f'  skipped {p.relative_to(ROOT)} ({why})')
    print(f'{len(changed)} updated, {len(skipped)} skipped')


if __name__ == '__main__':
    sys.exit(main())
