#!/usr/bin/env python3
"""Load assets/oai-conversions.js (ChatGPT Ads conversion events) on every page
that already has the OpenAI Pixel.

Places a marker block directly after the existing OpenAI Pixel snippet in <head>:
the snippet itself (loader, init, page_viewed) is never edited. Pages without the
Pixel are skipped, so the event script never runs where the Pixel is absent.

Run from the repo root:  python3 tools/oai-conversions.py
Idempotent: re-running replaces the existing block. Run again after adding new pages.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = '<!-- oai-conversions:start (generated by tools/oai-conversions.py; edit there, not here) -->'
END = '<!-- oai-conversions:end -->'
BLOCK = f'{START}\n<script src="/assets/oai-conversions.js" defer></script>\n{END}\n'

PIXEL_ID = 'RGbprxmJF4TT39HPvhcm7G'
# The protected Pixel snippet ends with this page_viewed call, then </script>.
ANCHOR_RE = re.compile(
    r'oaiq\("measure", "page_viewed", \{ type: "contents", contents: \[\{ id: location\.pathname, content_type: "page" \}\] \}\);\s*</script>\n?'
)
BLOCK_RE = re.compile(re.escape(START) + r'.*?' + re.escape(END) + r'\n?', re.S)
SKIP_DIRS = {'.git', 'docs', 'templates', 'vendor', 'tools'}


def main():
    changed, skipped = [], []
    for path in sorted(ROOT.rglob('*.html')):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        text = path.read_text(encoding='utf-8')
        if PIXEL_ID not in text:
            skipped.append(str(rel))
            continue
        base = BLOCK_RE.sub('', text)
        matches = list(ANCHOR_RE.finditer(base))
        if len(matches) != 1:
            sys.exit(f'STOP: {rel} has {len(matches)} protected page_viewed snippets (expected 1)')
        end = matches[0].end()
        new = base[:end] + BLOCK + base[end:]
        if new != text:
            path.write_text(new, encoding='utf-8')
            changed.append(str(rel))
    print(f'updated {len(changed)} pages; skipped {len(skipped)} without Pixel: {", ".join(skipped)}')


if __name__ == '__main__':
    main()
