#!/usr/bin/env python3
"""Store block + site footer for the two homepages: ONE template, TWO content sets.

Writes the same HTML structure into index.html (vi) and en/index.html (en), between the
markers below. Only text and link targets differ by language. Styles: assets/store-footer.css.

Run from the repo root:  python3 tools/store-footer.py
Edit the CONTENT dict to change wording; edit TEMPLATE to change structure (both pages follow).
"""
import pathlib, re, html, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
START = '<!-- store-footer:start (generated by tools/store-footer.py; edit there, not here) -->'
END = '<!-- store-footer:end -->'
CSS_LINK = '<link rel="stylesheet" href="/assets/store-footer.css">'

MAP_EMBED = 'https://www.google.com/maps?q=Manh%20Long%20Optical%2C%20147A%20L%C3%AA%20Du%E1%BA%A9n%2C%20C%E1%BB%ADa%20Nam%2C%20H%C3%A0%20N%E1%BB%99i&amp;output=embed'
MAP_DIR = 'https://www.google.com/maps/dir/?api=1&amp;destination=147A+L%C3%AA+Du%E1%BA%A9n,+C%E1%BB%ADa+Nam,+H%C3%A0+N%E1%BB%99i'
TEL = 'tel:+84777986999'
ZALO = 'https://zalo.me/0777986999'
WA = 'https://wa.me/84777986999'
MAIL = 'mailto:mlong.optical@gmail.com'

CONTENT = {
  'vi': dict(
    file='index.html',
    map_title='Bản đồ tới Manh Long Optical, 147A Lê Duẩn, Phường Cửa Nam, Hà Nội',
    map_button='Chỉ đường',
    kicker='Ghé cửa hàng',
    heading='Manh Long Optical, 147A Lê Duẩn',
    address_label='Địa chỉ',
    address_lines=['147A Lê Duẩn, Phường Cửa Nam, Hà Nội', 'Cách ga Hà Nội một đoạn đi bộ'],
    address_link=('/kinh-mat-gan-day.html', 'Giờ mở cửa, đường đi và giá tham khảo'),
    hours_label='Giờ mở cửa',
    hours_lines=['8:00 – 21:30', 'Tất cả các ngày, kể cả lễ'],
    contact_label='Liên hệ',
    directions_label='Đường đi',
    directions_link='Mở Google Maps',
    policies_label='Chính sách',
    policies=[('/dieu-khoan-dich-vu.html', 'Điều khoản dịch vụ'),
              ('/chinh-sach-thanh-toan.html', 'Chính sách thanh toán'),
              ('/chinh-sach-giao-hang.html', 'Chính sách giao hàng'),
              ('/chinh-sach-bao-hanh.html', 'Chính sách bảo hành'),
              ('/chinh-sach-doi-tra.html', 'Chính sách đổi trả'),
              ('/chinh-sach-bao-mat.html', 'Chính sách bảo mật và quyền riêng tư')],
    home='/',
    footer_links=[('/cua-hang.html#collection', 'Bộ sưu tập', ''),
                  ('/trong-kinh.html', 'Tròng kính', ''),
                  ('/uu-dai.html', 'Ưu đãi', ''),
                  ('/tim-hieu.html', 'Tìm hiểu', ''),
                  ('/cua-hang.html#store', 'Cửa hàng', ''),
                  ('/cau-hoi-thuong-gap.html', 'Hỏi đáp', ''),
                  ('/en/', 'English', 'en'),
                  (MAIL, 'Liên hệ', '')],
    base_lines=['Manh Long Optical Co., Ltd. · Hà Nội',
                '147A Lê Duẩn, Phường Cửa Nam, Hà Nội · Mở 8:00 – 21:30 hằng ngày · 0777 986 999'],
    policies_aria='Chính sách',
  ),
  'en': dict(
    file='en/index.html',
    map_title='Map to Manh Long Optical, 147A Le Duan, Cua Nam, Hanoi',
    map_button='Directions',
    kicker='Visit the store',
    heading='Manh Long Optical, 147A Lê Duẩn',
    address_label='Address',
    address_lines=['147A Lê Duẩn, Cửa Nam, Hanoi', 'A short walk from Hanoi Railway Station'],
    address_link=('/en/prescription-glasses-hanoi.html', 'Hours, directions and prices'),
    hours_label='Opening hours',
    hours_lines=['8:00 – 21:30', 'Every day, including holidays'],
    contact_label='Contact',
    directions_label='Directions',
    directions_link='Open Google Maps',
    policies_label='Policies',
    policies=[('/en/terms-of-service.html', 'Terms of Service'),
              ('/en/payment-policy.html', 'Payment Policy'),
              ('/en/delivery-policy.html', 'Delivery Policy'),
              ('/en/warranty-policy.html', 'Warranty Policy'),
              ('/en/returns-policy.html', 'Return &amp; Exchange Policy'),
              ('/en/privacy-policy.html', 'Privacy Policy')],
    home='/en/',
    footer_links=[('/cua-hang.html?lang=en#collection', 'Frames', ''),
                  ('/en/lenses.html', 'Lenses', ''),
                  ('/en/offers.html', 'Offers', ''),
                  ('/en/learn/', 'Learn', ''),
                  ('/en/frames.html#store', 'Store', ''),
                  ('/en/faq.html', 'Questions', ''),
                  ('/', 'Tiếng Việt', 'vi'),
                  (MAIL, 'Contact', '')],
    base_lines=['Manh Long Optical · Hanoi',
                '147A Lê Duẩn, Cửa Nam, Hanoi · Open 8:00 – 21:30 daily · 0777 986 999'],
    policies_aria='Policies',
  ),
}

def render(c):
    ext = 'target="_blank" rel="noopener"'
    addr = '<br>'.join(c['address_lines']) + '<br><a href="%s">%s</a>' % c['address_link']
    pol = ''.join('<li><a href="%s">%s</a></li>' % p for p in c['policies'])
    flinks = '\n'.join('      <li><a href="%s"%s>%s</a></li>' % (h, (' hreflang="%s" lang="%s"' % (l, l)) if l else '', t)
                       for h, t, l in c['footer_links'])
    base = '\n'.join('      <p>%s</p>' % b for b in c['base_lines'])
    return f'''{START}
<section class="storeblk">
  <div class="wrap split">
    <div class="storemap">
      <iframe title="{c['map_title']}" src="{MAP_EMBED}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      <a class="dir" href="{MAP_DIR}" {ext}>{c['map_button']}</a>
    </div>
    <div class="storeinfo">
      <p class="kicker">{c['kicker']}</p>
      <h2 class="big serif">{c['heading']}</h2>
      <dl class="storegrid">
        <div><dt>{c['address_label']}</dt><dd>{addr}</dd></div>
        <div><dt>{c['hours_label']}</dt><dd>{'<br>'.join(c['hours_lines'])}</dd></div>
        <div><dt>{c['contact_label']}</dt><dd><a href="{TEL}">0777 986 999</a><br><a href="{ZALO}" {ext}>Zalo</a> · <a href="{WA}" {ext}>WhatsApp</a><br><a href="{MAIL}">mlong.optical@gmail.com</a></dd></div>
        <div><dt>{c['directions_label']}</dt><dd><a href="{MAP_DIR}" {ext}>{c['directions_link']}</a></dd><dt class="spolicy-dt">{c['policies_label']}</dt><dd><ul class="spolicy" aria-label="{c['policies_aria']}">{pol}</ul></dd></div>
      </dl>
    </div>
  </div>
</section>
<footer class="sitefoot">
  <div class="wrap">
    <a class="fmark" href="{c['home']}">Mạnh Long</a>
    <ul class="flinks">
{flinks}
    </ul>
    <div class="fbase">
{base}
      <p class="fcopy">Copyright © 2026 Manh Long Optical. All rights reserved.</p>
    </div>
  </div>
</footer>
{END}'''

def apply(lang):
    c = CONTENT[lang]
    f = ROOT / c['file']
    s = f.read_text(encoding='utf-8')
    block = render(c)
    if START in s:
        s = re.sub(re.escape(START) + r'[\s\S]*?' + re.escape(END), lambda m: block, s, count=1)
    else:
        # first run: replace the existing store section and the last <footer> (must be adjacent)
        i = s.find('<section class="storeblk">')
        k = s.rfind('<footer')
        l = s.find('</footer>', k) + len('</footer>')
        if i < 0 or k < i:
            sys.exit('%s: store section / footer not found' % c['file'])
        between = s[s.find('</section>', i) + len('</section>'):k]
        prefix = ''
        if between.strip() == '</main>':
            prefix = '</main>\n'   # close <main> before the shared component, as on the VI page
        elif between.strip():
            sys.exit('%s: unexpected content between store section and footer' % c['file'])
        s = s[:i] + prefix + block + s[l:]
    if CSS_LINK not in s:
        s = s.replace('</head>', CSS_LINK + '\n</head>', 1)
    f.write_text(s, encoding='utf-8')
    print('wrote', c['file'])

if __name__ == '__main__':
    for lang in CONTENT:
        apply(lang)
